@host = http://localhost:3041/link
@UUid = 9dfea759-3f40-4f8c-85ed-1a65029d1dc7

###

GET {{host}}/

###

GET {{host}}/{{UUid}}

###

POST {{host}}
Content-Type: application/json

{
	"FcwebId": 28005,
  "Date_int": "2024-03-27T14:05:10.944Z",
  "Status_pg": "Falta pagamento"
}

###

PUT {{host}}/update/{{UUid}}
Content-Type: application/json
{
  "Status_pg": "Pago"
}

###

DELETE {{host}}/delete/{{UUid}}